### ISSUE TITLE
Add null check for appSettings.Secret

### ISSUE THREAD

**Issue by ryanis-online** [LaunchCodeLiftoffProjects/moore-market#28]
In `Startup.cs` on line 47, there is no null check to make sure that key is being set (i.e. if the user doesn't have the secret specified in their appsettings.json file). Let's add a null check that shuts the application down if there is no app secret since it technically can't be run anyways. Bonus points if we can add in a user friendly message that says something like "Hey you goof, you didn't give me an app secret!"

**Comment by iktani** [comment]
Ryan, should this bugfix be branched off develop or some other branch? I'll self-assign this.

**Comment by ryanis-online** [comment]
@iktani thanks for taking a look at this! Yes, please branch off of `develop`. For bugs in the "git-flow" style, they usually follow the convention `bug/<SHORT_DESCRIPTION`. So something like `bug/null-check` would suffice :)
